FROM docker.elastic.co/kibana/kibana:7.2.0
RUN kibana-plugin install https://repo1.maven.org/maven2/com/floragunn/search-guard-kibana-plugin/7.2.0-35.2.0/search-guard-kibana-plugin-7.2.0-35.2.0.zip
EXPOSE 5601
