FROM docker.elastic.co/kibana/kibana:6.8.0
RUN kibana-plugin install https://repo1.maven.org/maven2/com/floragunn/search-guard-kibana-plugin/6.8.0-18.4/search-guard-kibana-plugin-6.8.0-18.4.zip
EXPOSE 5601