FROM docker.elastic.co/kibana/kibana:7.1.1
RUN kibana-plugin install https://repo1.maven.org/maven2/com/floragunn/search-guard-kibana-plugin/7.1.1-35.1.0/search-guard-kibana-plugin-7.1.1-35.1.0.zip
EXPOSE 5601